[config]
default_to_workspace = false
skip_core_tasks = true

[env]
CARGO_TARGET_DIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/build/obj"
BIN_BASE = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/build/bin"
RDIR = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"

[tasks.default]
script = '''
echo "\nplease specify the task to make\n"
'''

[tasks.build]
disabled = true

[tasks.clear]
script = '''
rm -rf build
rm -rf vm_images
rm -rf src/sys/target
rm -rf src/boot/*/target
cd "${RDIR}/src/imager"
cargo clean
rm -rf target
cd "${RDIR}/src/bin"
rm -rf */target
cd "${RDIR}/src/sys"
rm -rf */target
rm -f lib/rt.vdso/rt.vdso
'''

[tasks.all]
dependencies = [
  "boot_img",
  "boot_img_release",
]

[tasks.boot_img]
dependencies = [
  "setup_dirs_debug",
  "x64_mbr_debug",
  "x64_boot_debug",
  "x64_kloader_debug",
  "kernel_debug",
  "rt_debug",
  "sys_io_debug",
  "sys_init_debug",
  "sys_log_debug",
  "sys_tty_debug",
  "sysbox_debug",
  "rush_debug",
  "httpd_debug",
  "httpd_axum_debug",
  "kibim_debug",
  "mdbg_debug",
  "rnetbench_debug",
  "systest_debug",
  "mio_test_debug",
  "tokio_tests_debug",
  "make_img_debug",
]

[tasks.boot_img_release]
dependencies = [
  "setup_dirs_release",
  "x64_mbr_release",
  "x64_boot_release",
  "x64_kloader_release",
  "kernel_release",
  "rt_release",
  "sys_io_release",
  "sys_init_release",
  "sys_log_release",
  "sys_tty_release",
  "sysbox_release",
  "rush_release",
  "httpd_release",
  "httpd_axum_release",
  "kibim_release",
  "mdbg_release",
  "rnetbench_release",
  "systest_release",
  "mio_test_release",
  "tokio_tests_release",
  "make_img_release",
]

# Cargo is confused when building kernel and the userspace binaries
# and rebuilds them. If working only with userspace, this task
# can be used to reduce compile/build time.
[tasks.u_dbg]
dependencies = [
  "setup_dirs_debug",
  "rt_debug",
  "sys_io_debug",
  "sys_init_debug",
  "sys_log_debug",
  "sys_tty_debug",
  "sysbox_debug",
  "rush_debug",
  "httpd_debug",
  "httpd_axum_debug",
  "kibim_debug",
  "mdbg_debug",
  "rnetbench_debug",
  "systest_debug",
  "mio_test_debug",
  "tokio_tests_debug",
  "make_img_debug",
]

# Cargo is confused when building kernel and the userspace binaries
# and rebuilds them. If working only with userspace, this task
# can be used to reduce compile/build time.
[tasks.u_rel]
dependencies = [
  "setup_dirs_release",
  "rt_release",
  "sys_io_release",
  "sys_init_release",
  "sys_log_release",
  "sys_tty_release",
  "sysbox_release",
  "rush_release",
  "httpd_release",
  "httpd_axum_release",
  "kibim_release",
  "mdbg_release",
  "rnetbench_release",
  "systest_release",
  "mio_test_release",
  "tokio_tests_release",
  "make_img_release",
]

[tasks.setup_dirs_debug]
env = { "MOTO_BIN" = "${BIN_BASE}/debug" }
script = '''
mkdir -p "${MOTO_BIN}"
'''

[tasks.setup_dirs_release]
env = { "MOTO_BIN" = "${BIN_BASE}/release" }
script = '''
mkdir -p "${MOTO_BIN}"
'''

[tasks.x64_mbr_debug]
cwd = "./src/boot/x64.mbr"
script = '''
./build.sh
'''

# Need a different debug|release tasks because the output dirs differ.
[tasks.x64_mbr_release]
cwd = "./src/boot/x64.mbr"
script = '''
./build.sh
'''

[tasks.x64_boot_debug]
cwd = "./src/boot/x64.boot"
script = '''
./build.sh
'''

# Need a different debug|release tasks because the output dirs differ.
[tasks.x64_boot_release]
cwd = "./src/boot/x64.boot"
script = '''
./build.sh
'''

[tasks.x64_kloader_debug]
cwd = "./src/boot/x64.kloader"
script = '''
./build.sh
'''

[tasks.x64_kloader_release]
cwd = "./src/boot/x64.kloader"
script = '''
./build.sh --release
'''

[tasks.kernel_debug]
cwd = "./src/sys/kernel"
script = '''
./build.sh
'''

[tasks.kernel_release]
cwd = "./src/sys/kernel"
script = '''
./build.sh --release
'''

[tasks.rt_debug]
cwd = "./src/sys/lib/rt.vdso"
script = '''
./build.sh
'''

[tasks.rt_release]
cwd = "./src/sys/lib/rt.vdso"
script = '''
./build.sh --release
'''

[tasks.sys_io_debug]
cwd = "./src/sys/sys-io"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/sys-io" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/sys-io"
'''

[tasks.sys_io_release]
cwd = "./src/sys/sys-io"
script = '''
# CARGO_LOG=cargo::core::compiler::fingerprint=info \
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/sys-io" "${MOTO_BIN}/sys-io"
'''

[tasks.sys_init_debug]
cwd = "./src/sys/sys-init"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/sys-init" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/sys-init"
'''

[tasks.sys_init_release]
cwd = "./src/sys/sys-init"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/sys-init" "${MOTO_BIN}/sys-init"
'''

[tasks.sys_log_debug]
cwd = "./src/sys/sys-log"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/sys-log" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/sys-log"
'''

[tasks.sys_log_release]
cwd = "./src/sys/sys-log"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/sys-log" "${MOTO_BIN}/sys-log"
'''

[tasks.sys_tty_debug]
cwd = "./src/sys/sys-tty"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/sys-tty" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/sys-tty"
'''

[tasks.sys_tty_release]
cwd = "./src/sys/sys-tty"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/sys-tty" "${MOTO_BIN}/sys-tty"
'''

[tasks.sysbox_debug]
cwd = "./src/sys/tools/sysbox"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/sysbox" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/sysbox"
'''

[tasks.sysbox_release]
cwd = "./src/sys/tools/sysbox"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/sysbox" "${MOTO_BIN}/sysbox"
'''

[tasks.systest_debug]
cwd = "./src/sys/tests/systest"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/systest" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/systest"
'''

[tasks.systest_release]
cwd = "./src/sys/tests/systest"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/systest" "${MOTO_BIN}/systest"
'''

[tasks.mio_test_debug]
cwd = "./src/sys/tests/mio-test"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/mio-test" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/mio-test"
'''

[tasks.mio_test_release]
cwd = "./src/sys/tests/mio-test"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/mio-test" "${MOTO_BIN}/mio-test"
'''

[tasks.tokio_tests_debug]
cwd = "./src/sys/tests/tokio-tests"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/tokio-tests" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/tokio-tests"
'''

[tasks.tokio_tests_release]
cwd = "./src/sys/tests/tokio_tests"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/tokio-tests" "${MOTO_BIN}/tokio-tests"
'''

[tasks.rush_debug]
cwd = "./src/bin/rush"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/rush" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/rush"
'''

[tasks.rush_release]
cwd = "./src/bin/rush"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/rush" "${MOTO_BIN}/rush"
'''

[tasks.httpd_debug]
cwd = "./src/bin/httpd"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/httpd" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/httpd"
'''

[tasks.httpd_release]
cwd = "./src/bin/httpd"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/httpd" "${MOTO_BIN}/httpd"
'''

[tasks.httpd_axum_debug]
cwd = "./src/bin/httpd-axum"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/httpd-axum" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/httpd-axum"
'''

[tasks.httpd_axum_release]
cwd = "./src/bin/httpd-axum"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/httpd-axum" "${MOTO_BIN}/httpd-axum"
'''

[tasks.kibim_debug]
cwd = "./src/bin/kibim"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/kibim" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/kibim"
'''

[tasks.kibim_release]
cwd = "./src/bin/kibim"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/kibim" "${MOTO_BIN}/kibim"
'''

[tasks.mdbg_debug]
cwd = "./src/sys/tools/mdbg"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/mdbg" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/mdbg"
'''

[tasks.mdbg_release]
cwd = "./src/sys/tools/mdbg"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/mdbg" "${MOTO_BIN}/mdbg"
'''

[tasks.rnetbench_debug]
cwd = "./src/bin/rnetbench"
script = '''
cargo +dev-x86_64-unknown-moturus build --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --target x86_64-unknown-moturus
strip -o "${MOTO_BIN}/rnetbench" "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/debug/rnetbench"
'''

[tasks.rnetbench_release]
cwd = "./src/bin/rnetbench"
script = '''
cargo +dev-x86_64-unknown-moturus build --release --target x86_64-unknown-moturus
cargo +dev-x86_64-unknown-moturus clippy --release --target x86_64-unknown-moturus
cp "${CARGO_TARGET_DIR}/x86_64-unknown-moturus/release/rnetbench" "${MOTO_BIN}/rnetbench"
'''

[tasks.make_img_debug]
cwd = "./src/imager"
script = '''
cargo clippy
cargo run --release -- ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} debug
cp "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/src/vm_scripts/"* \
   "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/vm_images/debug/"
'''

[tasks.make_img_release]
cwd = "./src/imager"
script = '''
cargo clippy
cargo run --release -- ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY} release
cp "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/src/vm_scripts/"* \
   "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/vm_images/release/"
'''

