[workspace]
members = [
  # system libraries
  "lib/flatfs",
  "lib/frusa",
  "lib/rt.vdso",
  "lib/moto-io-internal",
  "lib/moto-ipc",
  "lib/moto-log",
  "lib/moto-mpmc",
  "lib/moto-rt",
  "lib/moto-sys",
  "lib/moto-sys-io",
  "lib/srfs",
  "lib/srfs-core",
  "lib/timeq",
  "lib/virtio",

  # system binaries
  "kernel",
  "sys-init",
  "sys-io",
  "sys-log",
  "sys-tty",

  # tools
  "tools/mdbg",
  "tools/sysbox",

  # tests
  "tests/crossbench",
  "tests/mio-test",
  "tests/systest",
  "tests/tokio-tests",
]
resolver = "2"

[patch.crates-io]
flatfs       = { path = "lib/flatfs"          }
moto-ipc     = { path = "lib/moto-ipc"        }
moto-log     = { path = "lib/moto-log"        }
moto-rt      = { path = "lib/moto-rt"         }
moto-sys     = { path = "lib/moto-sys"        }
moto-sys-io  = { path = "lib/moto-sys-io"     }
moto-virtio  = { path = "lib/virtio"          }
srfs-core    = { path = "lib/srfs-core"       }
srfs         = { path = "lib/srfs"            }

mio          = { git = "https://github.com/moturus/mio.git", branch = "mio-moturus-v1.0.1" }
tokio        = { git = "https://github.com/moturus/tokio.git", branch = "tokio-moturus-1.44.2" }

getrandom    = { path = "../third_party/getrandom-0.2.16", features = ["rdrand"]}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
codegen-units = 1
