pub fn map_err_into_native(err: std::io::Error) -> moto_rt::Error {
    match err.kind() {
        std::io::ErrorKind::NotFound => moto_rt::Error::NotFound,
        std::io::ErrorKind::PermissionDenied => moto_rt::Error::NotAllowed,
        std::io::ErrorKind::ConnectionRefused => moto_rt::Error::NotConnected,
        std::io::ErrorKind::ConnectionReset => moto_rt::Error::NotConnected,
        std::io::ErrorKind::HostUnreachable => moto_rt::Error::NotConnected,
        std::io::ErrorKind::NetworkUnreachable => moto_rt::Error::NotConnected,
        std::io::ErrorKind::ConnectionAborted => moto_rt::Error::NotConnected,
        std::io::ErrorKind::NotConnected => moto_rt::Error::NotConnected,
        std::io::ErrorKind::AddrInUse => todo!(),
        std::io::ErrorKind::AddrNotAvailable => todo!(),
        std::io::ErrorKind::NetworkDown => moto_rt::Error::NotConnected,
        std::io::ErrorKind::BrokenPipe => moto_rt::Error::NotConnected,
        std::io::ErrorKind::AlreadyExists => moto_rt::Error::AlreadyInUse,
        std::io::ErrorKind::WouldBlock => moto_rt::Error::NotReady,
        std::io::ErrorKind::NotADirectory => moto_rt::Error::NotADirectory,
        std::io::ErrorKind::IsADirectory => todo!(),
        std::io::ErrorKind::DirectoryNotEmpty => todo!(),
        std::io::ErrorKind::ReadOnlyFilesystem => todo!(),
        std::io::ErrorKind::FilesystemLoop => todo!(),
        std::io::ErrorKind::StaleNetworkFileHandle => todo!(),
        std::io::ErrorKind::InvalidInput => moto_rt::Error::InvalidArgument,
        std::io::ErrorKind::InvalidData => moto_rt::Error::InvalidData,
        std::io::ErrorKind::TimedOut => moto_rt::Error::TimedOut,
        std::io::ErrorKind::WriteZero => todo!(),
        std::io::ErrorKind::StorageFull => todo!(),
        std::io::ErrorKind::NotSeekable => todo!(),
        std::io::ErrorKind::QuotaExceeded => todo!(),
        std::io::ErrorKind::FileTooLarge => todo!(),
        std::io::ErrorKind::ResourceBusy => todo!(),
        std::io::ErrorKind::ExecutableFileBusy => todo!(),
        std::io::ErrorKind::Deadlock => todo!(),
        std::io::ErrorKind::CrossesDevices => todo!(),
        std::io::ErrorKind::TooManyLinks => todo!(),
        std::io::ErrorKind::InvalidFilename => todo!(),
        std::io::ErrorKind::ArgumentListTooLong => todo!(),
        std::io::ErrorKind::Interrupted => todo!(),
        std::io::ErrorKind::Unsupported => todo!(),
        std::io::ErrorKind::UnexpectedEof => todo!(),
        std::io::ErrorKind::OutOfMemory => moto_rt::Error::OutOfMemory,
        std::io::ErrorKind::Other => moto_rt::Error::Unknown,
        _ => moto_rt::Error::Unknown,
    }
}

pub fn map_native_error(err: moto_rt::Error) -> std::io::Error {
    std::io::Error::from_raw_os_error(err as u16 as i32)
}
