[package]
name = "sysbox"
authors = ["The Motor OS Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
moto-ipc     = { path = "../../lib/moto-ipc"    }
moto-rt      = { path = "../../lib/moto-rt"     }
moto-sys     = { path = "../../lib/moto-sys"    }
moto-sys-io  = { path = "../../lib/moto-sys-io", features = ["std"] }
time = { version = "0.3.36", default-features = false, features = ["std"] }

