[package]
name = "sys-init"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
moto-sys     = { path = "../lib/moto-sys"    }
moto-log     = { path = "../lib/moto-log"    }

log = "=0.4.27"
shell-words = "1.1"