[package]
name = "russhd"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger   = "=0.11.8"
hex          = "0.4.3"
log          = "=0.4.27"
russh        = "=0.52.0"
rand_core    = "0.6"
serde        = { version = "1.0.*", features = ["derive"] }
sha2         = "=0.10.8"
shell-words  = "1.1"
tokio        = { version = "=1.47.1", features = ["process", "rt", "sync"] }
toml         = "0.8.10"

[target.'cfg(target_os = "motor")'.dependencies]
moto-log     = { path = "../../sys/lib/moto-log" }
moto-rt      = { path = "../../sys/lib/moto-rt"  }
moto-sys     = { path = "../../sys/lib/moto-sys" }

[dev-dependencies]
ssh-encoding = "0.2.0"

[patch.crates-io]
mio   = { git = "https://github.com/moturus/mio.git"  , branch = "mio-motor-v1.0.4_2025-10-07"   }
tokio = { git = "https://github.com/moturus/tokio.git", branch = "tokio-motor-1.47.1_2025-10-07" }

getrandom       = { path = "../../third_party/getrandom-0.2.16"       , features = ["rdrand"]}
home            = { path = "../../third_party/home-0.5.11"            }
russh-cryptovec = { path = "../../third_party/russh-cryptovec-0.52.0" }
