[package]
name = "moto-sys"
version = "0.3.0"
authors = ["The Motor OS Project Developers"]
license = "MIT OR Apache-2.0"
keywords = ["motor", "motor-os"]
readme = "README.md"
repository = "https://github.com/moturus/moto-sys"
description = "Motor OS system crate."
edition = "2021"

[dependencies]
moto-rt = { version = "0.17.6", path = "../moto-rt", optional = true }

[features]
base = ["moto-rt/base"]
default = ["userspace"]
userspace = ["moto-rt"]
