use std::{
    sync::{
        Arc,
        atomic::{AtomicU32, AtomicU64, Ordering},
    },
    task::Poll,
    time::Duration,
};

use futures::FutureExt;
use moto_async::AsFuture;
use moto_rt::time::Instant;
use moto_sys::{SysCpu, SysHandle};

fn test_basic() {
    assert_eq!(42, moto_async::LocalRuntime::new().block_on(async { 42 }));
    println!("----- moto_async::test_basic PASS");
}

// A timeout future that returns the number of polls it got.
struct TimeoutFuture {
    polls: u64,
    inner: moto_async::Sleep,
}

impl TimeoutFuture {
    fn new(timo: std::time::Duration) -> Self {
        Self {
            polls: 0,
            inner: moto_async::Sleep::new_timeout(Instant::now() + timo),
        }
    }
}

impl core::future::Future for TimeoutFuture {
    type Output = u64;

    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        self.polls += 1;
        match self.inner.poll_unpin(cx) {
            Poll::Ready(_) => Poll::Ready(self.polls),
            Poll::Pending => Poll::Pending,
        }
    }
}

fn test_timeout() {
    let start = Instant::now();
    let timo = std::time::Duration::from_millis(15);

    let fut = TimeoutFuture::new(timo);

    // Make sure that the future got at most two polls:
    // one the initial pending, and one the final ready.
    // If there are delays, the first poll may be ready.
    let poll_calls = moto_async::LocalRuntime::new().block_on(fut);
    assert!(start.elapsed() >= timo);

    if poll_calls == 1 {
        log::info!("test_timeout: a single poll() call");
    } else if poll_calls > 2 {
        panic!("Too many poll calls: {poll_calls}.");
    }

    println!("----- moto_async::test_timeout PASS");
}

fn test_select() {
    let counter = Arc::new(AtomicU32::new(0));

    let c1 = counter.clone();
    let c2 = counter.clone();

    let f1 = async move {
        moto_async::sleep(Duration::from_millis(50)).await;

        c1.fetch_add(1, Ordering::AcqRel);
    };

    let f2 = async move {
        moto_async::sleep(Duration::from_millis(150)).await;

        c2.fetch_add(2, Ordering::AcqRel);
    };

    let res = moto_async::LocalRuntime::new().block_on(async move {
        futures::select! {_ = f1.fuse() => 1, _ = f2.fuse() => 2}
    });

    assert_eq!(1, res);
    assert_eq!(1, counter.load(Ordering::Acquire));

    println!("----- moto_async::test_select PASS");
}

fn test_spawn() {
    moto_async::LocalRuntime::new().block_on(async {
        let join_1 = moto_async::LocalRuntime::spawn(async {
            moto_async::sleep(Duration::from_millis(20)).await;
            42
        });

        let join_2 = moto_async::LocalRuntime::spawn(async {
            moto_async::sleep(Duration::from_millis(40)).await;
            "foobar"
        });

        assert_eq!("foobar", join_2.await);
        assert_eq!(42, join_1.await);
    });
    println!("----- moto_async::test_spawn PASS");
}

fn test_interleaving() {
    use std::cell::RefCell;
    use std::rc::Rc;

    // Note: this test was generated by Gemini Pro 2.5 and modified by a human.
    let log = Rc::new(RefCell::new(Vec::new()));

    moto_async::LocalRuntime::new().block_on(async {
        // Spawn three tasks, each with a different sleep duration.
        let log1 = log.clone();
        let h1 = moto_async::LocalRuntime::spawn(async move {
            log1.borrow_mut().push(1);
            moto_async::sleep(Duration::from_millis(30)).await;
            log1.borrow_mut().push(6);
        });

        let log2 = log.clone();
        let h2 = moto_async::LocalRuntime::spawn(async move {
            log2.borrow_mut().push(2);
            moto_async::sleep(Duration::from_millis(20)).await;
            log2.borrow_mut().push(5);
        });

        let log3 = log.clone();
        let h3 = moto_async::LocalRuntime::spawn(async move {
            log3.borrow_mut().push(3);
            moto_async::sleep(Duration::from_millis(10)).await;
            log3.borrow_mut().push(4);
        });

        h1.await;
        h2.await;
        h3.await;

        assert_eq!(
            *log.borrow(),
            vec![1, 2, 3, 4, 5, 6],
            "Tasks didn't interleave as expected."
        );
    });

    println!("----- moto_async::test_interleaving PASS");
}

fn test_nested_tasks() {
    // Note: this test was generated by Gemini Pro 2.5 and modified by a human.
    moto_async::LocalRuntime::new().block_on(async {
        let handle_a = moto_async::LocalRuntime::spawn(async {
            let handle_b = moto_async::LocalRuntime::spawn(async {
                moto_async::sleep(Duration::from_millis(10)).await;
                1337
            });
            let value_from_b = handle_b.await;
            format!("Task A processed value: {}", value_from_b)
        });

        let final_result = handle_a.await;
        assert_eq!(
            final_result, "Task A processed value: 1337",
            "Value should be correctly propagated from child to parent"
        );
    });
    println!("----- moto_async::test_nested_tasks PASS");
}

fn test_event_stream() {
    // Test ping-pong across threads.
    const ITERS: u32 = 100;
    let (handle_here, handle_there) =
        moto_sys::SysObj::create_ipc_pair(SysHandle::SELF, SysHandle::SELF, 0).unwrap();

    let channel_here = Arc::new(AtomicU32::new(0));
    let channel_there = channel_here.clone();

    let runtime_thread = std::thread::spawn(move || {
        moto_async::LocalRuntime::new().block_on(async move {
            for step in 0..ITERS {
                assert_eq!(step * 2, channel_there.fetch_add(1, Ordering::AcqRel));
                moto_sys::SysCpu::wake(handle_there).unwrap();
                handle_there.as_future().await.unwrap();
            }
        })
    });

    for step in 0..ITERS {
        let mut handles = [handle_here];
        moto_sys::SysCpu::wait(&mut handles, SysHandle::NONE, SysHandle::NONE, None).unwrap();
        assert_eq!(step * 2 + 1, channel_here.fetch_add(1, Ordering::AcqRel));
        moto_sys::SysCpu::wake(handle_here).unwrap();
    }

    runtime_thread.join().unwrap();
    println!("----- moto_async::test_event_stream PASS");
}

fn test_wake_exit_race() {
    let (handle_here, handle_there) =
        moto_sys::SysObj::create_ipc_pair(SysHandle::SELF, SysHandle::SELF, 0).unwrap();

    let runtime_thread = std::thread::spawn(move || {
        moto_async::LocalRuntime::new().block_on(async move {
            for _ in 0..5 {
                futures::select! {
                    _ = handle_there.as_future().fuse() => (),
                    _ = moto_async::sleep(Duration::from_millis(20)).fuse() => (),
                };
            }
        });
    });

    for _ in 0..5 {
        std::thread::sleep(Duration::from_millis(20));
        moto_sys::SysCpu::wake(handle_here).unwrap();
    }

    runtime_thread.join().unwrap();

    println!("----- moto_async::test_wake_exit_race PASS");
}

fn test_mutex() {
    // The test is based on a test was generated by Gemini 2.5 Pro.
    const NUM_TASKS: usize = 100;
    let start = std::time::Instant::now();
    moto_async::LocalRuntime::new().block_on(async {
        let counter = std::rc::Rc::new(moto_async::LocalMutex::new(0_usize));

        let mut tasks = Vec::with_capacity(NUM_TASKS);

        for _ in 0..NUM_TASKS {
            let counter_clone = counter.clone();

            let task = moto_async::LocalRuntime::spawn(async move {
                let mut num = counter_clone.lock().await;
                *num += 1;
            });
            tasks.push(task);
        }

        for task in tasks {
            task.await;
        }

        let final_count = *counter.lock().await;
        assert_eq!(
            final_count, NUM_TASKS,
            "The final count should equal the number of tasks spawned."
        );
    });
    println!(
        "----- moto_async::test_mutex PASS ({NUM_TASKS} tasks in {:?})",
        start.elapsed()
    );
}

fn test_mutex_cancel_safety() {
    // The test is based on a test was generated by Gemini 2.5 Pro.
    moto_async::LocalRuntime::new().block_on(async {
        let mutex = std::rc::Rc::new(moto_async::LocalMutex::new(0_usize));
        let initial_lock = mutex.lock().await;

        let mutex_clone = mutex.clone();
        let cancel_task = moto_async::LocalRuntime::spawn(async move {
            let f1 = mutex_clone.lock();
            let f2 = moto_async::sleep(Duration::from_millis(20));
            let res = futures::select! {_ = f1.fuse() => 1, _ = f2.fuse() => 2};
            assert_eq!(res, 2);
        });

        // Sleep a bit so that f1 above gets polled.
        moto_async::sleep(Duration::from_millis(10)).await;

        // Spawn a second mutex waiter.
        let mutex_clone = mutex.clone();
        let later_task = moto_async::LocalRuntime::spawn(async move {
            *mutex_clone.lock().await += 1;
        });

        cancel_task.await;

        // The initial lock still holds.
        assert_eq!(0, *initial_lock);

        drop(initial_lock);
        later_task.await;

        // The later task has incremented the mutex.
        assert_eq!(*mutex.lock().await, 1);
    });
    println!("----- moto_async::test_mutex_cancel_safety PASS");
}

pub fn test_oneshot() {
    let (sender_ping, receiver_ping) = moto_async::oneshot();
    let (sender_pong, receiver_pong) = moto_async::oneshot();

    let runtime_thread = std::thread::spawn(move || {
        moto_async::LocalRuntime::new().block_on(async move {
            let val = receiver_ping.await.unwrap();
            assert_eq!(val, 42);
            sender_pong.send(43_u32).unwrap();
        });
    });

    std::thread::sleep(Duration::from_millis(10));
    sender_ping.send(42_u32).unwrap();

    moto_async::LocalRuntime::new().block_on(async move {
        let val = receiver_pong.await.unwrap();
        assert_eq!(val, 43);
    });

    let _ = runtime_thread.join();

    println!("----- moto_async::test_oneshot PASS");
}

fn test_channel_basic() {
    moto_async::LocalRuntime::new().block_on(async move {
        let (tx, mut rx) = moto_async::channel::<usize>(2);

        assert!(tx.send(1).await.is_ok());
        assert!(tx.send(2).await.is_ok());

        assert_eq!(rx.recv().await, Some(1));
        assert_eq!(rx.recv().await, Some(2));

        moto_async::LocalRuntime::spawn(async move {
            tx.send(99).await.unwrap();
        });

        assert_eq!(rx.recv().await, Some(99));
    });

    println!("----- moto_async::test_channel_basic PASS");
}

const SENDERS: u32 = 2;
const CHANNEL_CAPACITY: usize = 16;

fn test_moto_channel_multithreaded() {
    const ITERS: u32 = 100_000;

    moto_async::LocalRuntime::new().block_on(async move {
        let (tx, mut rx) = moto_async::channel::<u32>(CHANNEL_CAPACITY);

        let start = std::time::Instant::now();
        // Spawn sender threads.
        for sender in 0..SENDERS {
            let tx_clone = tx.clone();
            std::thread::spawn(move || {
                moto_async::LocalRuntime::new().block_on(async move {
                    for iter in 0..ITERS {
                        tx_clone
                            .send(sender * ITERS + iter)
                            .await
                            .expect("Send failed.");
                    }
                });
            });
        }

        // Drop tx so the receiver knows when to stop.
        drop(tx);

        let mut received_count = 0;

        // The receiver Loop.
        while let Some(_val) = rx.recv().await {
            received_count += 1;
        }

        let elapsed = start.elapsed();
        let cpu_usage = crate::mpmc::get_cpu_usage();

        assert_eq!(
            received_count,
            SENDERS * ITERS,
            "Did not receive all messages"
        );

        println!(
            "      Moto channel: {SENDERS}x{ITERS} messages in {elapsed:.2?}: {:.2} msg/usec.",
            ((SENDERS * ITERS) as f64) / (elapsed.as_nanos() as f64 * 0.001)
        );

        print!("\tcpu usage: ");
        for n in &cpu_usage {
            print!("{: >5.1}% ", (*n) * 100.0);
        }
        println!();
    });

    println!("----- moto_async::test_moto_channel_multithreaded PASS");
}

fn test_futures_channel_multithreaded() {
    const ITERS: u32 = 10_000;

    futures::executor::block_on(async move {
        use futures::sink::SinkExt;
        use futures::stream::StreamExt;

        let (tx, mut rx) = futures::channel::mpsc::channel::<u32>(CHANNEL_CAPACITY);

        let start = std::time::Instant::now();
        // Spawn sender threads.
        for sender in 0..SENDERS {
            let mut tx_clone = tx.clone();
            std::thread::spawn(move || {
                futures::executor::block_on(async move {
                    for iter in 0..ITERS {
                        tx_clone
                            .send(sender * ITERS + iter)
                            .await
                            .expect("Send failed.");
                    }
                });
            });
        }

        // Drop tx so the receiver knows when to stop.
        drop(tx);

        let mut received_count = 0;

        // The receiver Loop.
        while let Some(_val) = rx.next().await {
            received_count += 1;
        }

        let elapsed = start.elapsed();
        let cpu_usage = crate::mpmc::get_cpu_usage();

        assert_eq!(
            received_count,
            SENDERS * ITERS,
            "Did not receive all messages"
        );

        println!(
            "      Futures channel: {SENDERS}x{ITERS} messages in {elapsed:.2?}: {:.2} msg/usec.",
            ((SENDERS * ITERS) as f64) / (elapsed.as_nanos() as f64 * 0.001)
        );

        print!("\tcpu usage: ");
        for n in &cpu_usage {
            print!("{: >5.1}% ", (*n) * 100.0);
        }
        println!();
    });

    println!("----- moto_async::test_futures_channel_multithreaded PASS");
}

fn test_sync_waiter_signal_coalescing() {
    let waiter = moto_async::SyncWaiter::new();

    // Multiple signals with no waiter coalesce into one.
    waiter.signal();
    waiter.signal();
    waiter.signal();

    let start = Instant::now();
    waiter.wait(None);
    assert!(start.elapsed() < Duration::from_millis(100));

    // The coalesced signal is consumed: this wait must run to deadline.
    let timo = Duration::from_millis(30);
    let start = Instant::now();
    waiter.wait(Some(Instant::now() + timo));
    assert!(start.elapsed() >= timo);

    println!("----- moto_async::test_sync_waiter_signal_coalescing PASS");
}

fn test_sync_waiter_cross_thread() {
    let waiter = Arc::new(moto_async::SyncWaiter::new());
    let done = Arc::new(AtomicU32::new(0));

    let waiter_clone = waiter.clone();
    let done_clone = done.clone();
    let thread = std::thread::spawn(move || {
        while done_clone.load(Ordering::Acquire) == 0 {
            waiter_clone.wait(None);
        }
    });

    std::thread::sleep(Duration::from_millis(20));

    // Signal from inside a runtime task: allowed by contract.
    moto_async::LocalRuntime::new().block_on(async {
        done.store(1, Ordering::Release);
        waiter.signal();
    });

    thread.join().unwrap();
    println!("----- moto_async::test_sync_waiter_cross_thread PASS");
}

fn test_sync_waiter_ping_pong() {
    // Race stress: signal-while-parked, signal-before-wait, and
    // timeout-vs-signal races (one side waits with a short deadline).
    const ITERS: u32 = 5_000;

    let ping = Arc::new(moto_async::SyncWaiter::new());
    let pong = Arc::new(moto_async::SyncWaiter::new());
    let counter = Arc::new(AtomicU32::new(0));

    let ping_clone = ping.clone();
    let pong_clone = pong.clone();
    let counter_clone = counter.clone();
    let thread = std::thread::spawn(move || {
        for step in 0..ITERS {
            while counter_clone.load(Ordering::Acquire) != step * 2 {
                ping_clone.wait(Some(Instant::now() + Duration::from_millis(1)));
            }
            counter_clone.store(step * 2 + 1, Ordering::Release);
            pong_clone.signal();
        }
    });

    for step in 0..ITERS {
        while counter.load(Ordering::Acquire) != step * 2 + 1 {
            pong.wait(None);
        }
        counter.store(step * 2 + 2, Ordering::Release);
        ping.signal();
    }

    thread.join().unwrap();
    assert_eq!(counter.load(Ordering::Acquire), ITERS * 2);
    println!("----- moto_async::test_sync_waiter_ping_pong PASS");
}

fn test_block_on_sync_ready() {
    assert_eq!(42, moto_async::block_on_sync(async { 42 }));
    println!("----- moto_async::test_block_on_sync_ready PASS");
}

fn test_block_on_sync_cross_thread() {
    let (tx, rx) = moto_async::oneshot();
    let thread = std::thread::spawn(move || {
        std::thread::sleep(Duration::from_millis(20));
        tx.send(7_u32).unwrap();
    });

    assert_eq!(7, moto_async::block_on_sync(async { rx.await.unwrap() }));
    thread.join().unwrap();
    println!("----- moto_async::test_block_on_sync_cross_thread PASS");
}

fn test_block_on_sync_self_wake() {
    // Wake-before-park on every poll: exercises the parker's NOTIFIED
    // fast path and cached-waker reuse across calls.
    struct SelfWake {
        remaining: u32,
    }

    impl core::future::Future for SelfWake {
        type Output = ();

        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> Poll<Self::Output> {
            if self.remaining == 0 {
                return Poll::Ready(());
            }
            self.remaining -= 1;
            cx.waker().wake_by_ref();
            Poll::Pending
        }
    }

    for _ in 0..1000 {
        moto_async::block_on_sync(SelfWake { remaining: 10 });
    }
    println!("----- moto_async::test_block_on_sync_self_wake PASS");
}

fn test_block_on_sync_deadline() {
    // Completion before the deadline.
    let (tx, rx) = moto_async::oneshot();
    let thread = std::thread::spawn(move || {
        std::thread::sleep(Duration::from_millis(10));
        tx.send(5_u32).unwrap();
    });
    match moto_async::block_on_sync_deadline(rx, Instant::now() + Duration::from_secs(5)) {
        Ok(val) => assert_eq!(val.unwrap(), 5),
        Err(_) => panic!("unexpected deadline"),
    }
    thread.join().unwrap();

    // Timeout hands the future back with its partial progress intact:
    // two self-wakes, then quiet until the final poll at the deadline.
    struct Progress {
        polls: u32,
    }

    impl core::future::Future for Progress {
        type Output = ();

        fn poll(
            mut self: std::pin::Pin<&mut Self>,
            cx: &mut std::task::Context<'_>,
        ) -> Poll<Self::Output> {
            self.polls += 1;
            if self.polls < 3 {
                cx.waker().wake_by_ref();
            }
            Poll::Pending
        }
    }

    let timo = Duration::from_millis(30);
    let start = Instant::now();
    let Err(progress) = moto_async::block_on_sync_deadline(Progress { polls: 0 }, start + timo)
    else {
        panic!("Progress future completed?");
    };
    assert!(start.elapsed() >= timo);
    assert!(progress.polls >= 4, "polls: {}", progress.polls);

    println!("----- moto_async::test_block_on_sync_deadline PASS");
}

fn test_local_notify_eager() {
    moto_async::LocalRuntime::new().block_on(async move {
        let notify = moto_async::LocalNotify::new();

        // 1. We notify BEFORE we await.
        notify.notify_one();

        // 2. This should resolve instantly without yielding to the executor,
        // because `notified` was already set to true.
        notify.notified().await;
    });
    println!("----- moto_async::test_local_notify_eager PASS");
}

fn test_local_notify_deferred() {
    moto_async::LocalRuntime::new().block_on(async move {
        let notify = std::rc::Rc::new(moto_async::LocalNotify::new());
        let notify_clone = notify.clone();

        let task_completed = std::rc::Rc::new(std::cell::Cell::new(false));
        let task_completed_clone = task_completed.clone();

        // 1. Spawn a background task that sleeps until notified
        moto_async::LocalRuntime::spawn(async move {
            notify_clone.notified().await;
            task_completed_clone.set(true);
        });

        // 2. Yield the current thread. The background task will start,
        // poll `notified()`, receive `Poll::Pending`, and store its Waker.
        moto_async::yield_now().await;

        // Ensure the task is actually asleep and hasn't completed yet
        assert!(!task_completed.get());

        // 3. Fire the notification! This extracts the Waker and calls wake()
        notify.notify_one();

        // 4. Yield again. The executor sees the task was woken up,
        // runs it, and the task completes.
        moto_async::yield_now().await;

        // Verify the background task finished
        assert!(task_completed.get());
    });
    println!("----- moto_async::test_local_notify_deferred PASS");
}

fn test_local_notify_multi_waiter() {
    moto_async::LocalRuntime::new().block_on(async move {
        let notify = std::rc::Rc::new(moto_async::LocalNotify::new());
        let done = std::rc::Rc::new(std::cell::Cell::new((false, false, false)));

        for i in 0..3 {
            let notify = notify.clone();
            let done = done.clone();
            moto_async::LocalRuntime::spawn(async move {
                notify.notified().await;
                let mut val = done.get();
                match i {
                    0 => val.0 = true,
                    1 => val.1 = true,
                    _ => val.2 = true,
                }
                done.set(val);
            });
        }
        moto_async::yield_now().await;

        // notify_one is FIFO: waiters complete in spawn order.
        notify.notify_one();
        moto_async::yield_now().await;
        assert_eq!(done.get(), (true, false, false));

        // notify_all completes the rest.
        notify.notify_all();
        moto_async::yield_now().await;
        assert_eq!(done.get(), (true, true, true));

        // notify_all stored no permit: a fresh waiter stays pending.
        let pending = notify.notified();
        futures::select! {
            _ = futures::FutureExt::fuse(pending) => panic!("permit after notify_all?"),
            _ = moto_async::sleep(Duration::from_millis(10)).fuse() => (),
        }
    });
    println!("----- moto_async::test_local_notify_multi_waiter PASS");
}

fn test_local_notify_cancel_redispatch() {
    moto_async::LocalRuntime::new().block_on(async move {
        let notify = moto_async::LocalNotify::new();

        let first = notify.notified();
        let second = notify.notified();

        // Fires `first` (the oldest); dropping it un-consumed must pass
        // the notification to `second`.
        notify.notify_one();
        drop(first);

        futures::select! {
            _ = futures::FutureExt::fuse(second) => (),
            _ = moto_async::sleep(Duration::from_millis(100)).fuse() => {
                panic!("cancelled notification was lost")
            }
        }
    });
    println!("----- moto_async::test_local_notify_cancel_redispatch PASS");
}

fn test_local_notify_notify_all_cancel() {
    moto_async::LocalRuntime::new().block_on(async move {
        let notify = moto_async::LocalNotify::new();

        let first = notify.notified();
        let second = notify.notified();

        // Both waiters are part of this broadcast. Cancelling one must not
        // transfer its broadcast wake or manufacture a stored permit.
        notify.notify_all();
        drop(first);
        second.await;

        let late = notify.notified();
        futures::select! {
            _ = futures::FutureExt::fuse(late) => {
                panic!("cancelled notify_all waiter left a permit")
            }
            _ = moto_async::sleep(Duration::from_millis(10)).fuse() => (),
        }
    });
    println!("----- moto_async::test_local_notify_notify_all_cancel PASS");
}

fn test_wake_elision_counters() {
    let (issued_0, elided_0) = moto_async::wake_counters();

    // Busy receiver + foreign-thread sender: most sender wakes should
    // land while the receiver runtime is polling and be elided.
    moto_async::LocalRuntime::new().block_on(async {
        let (tx, mut rx) = moto_async::channel::<u32>(64);
        std::thread::spawn(move || {
            moto_async::LocalRuntime::new().block_on(async move {
                for i in 0..10_000 {
                    tx.send(i).await.unwrap();
                }
            });
        });

        let mut count = 0;
        while rx.recv().await.is_some() {
            count += 1;
        }
        assert_eq!(count, 10_000);
    });

    let (issued, elided) = moto_async::wake_counters();
    // Wakes happened; elision ratio is scheduling-dependent, so only log it.
    assert!(issued + elided > issued_0 + elided_0);
    println!(
        "----- moto_async::test_wake_elision_counters PASS (issued {} elided {})",
        issued - issued_0,
        elided - elided_0
    );
}

fn test_for_each_concurrent() {
    use futures::StreamExt;

    // Regression test for the waker-contract fix: a timer registered under
    // FuturesUnordered used to decode the combinator's waker as a task id
    // and hang, so for_each_concurrent never completed.
    let count = std::cell::Cell::new(0u32);
    moto_async::LocalRuntime::new().block_on(
        futures::stream::iter(0..100u32).for_each_concurrent(8, |_| async {
            moto_async::sleep(Duration::from_micros(100)).await;
            count.set(count.get() + 1);
        }),
    );
    assert_eq!(count.get(), 100);
    println!("----- moto_async::test_for_each_concurrent PASS");
}

// Helper for the wake_on_sleep tests: a thread expecting exactly one wake
// on its handle - it fails on a second wake within its 50ms window.
fn spawn_wake_probe() -> (std::thread::JoinHandle<()>, SysHandle) {
    let handle_slot = Arc::new(AtomicU64::new(0));
    let handle_clone = handle_slot.clone();
    let probe = std::thread::spawn(move || {
        handle_clone.store(moto_sys::current_thread().as_u64(), Ordering::Release);
        SysCpu::wait(&mut [], SysHandle::NONE, SysHandle::NONE, None).unwrap();
        let res = SysCpu::wait(
            &mut [],
            SysHandle::NONE,
            SysHandle::NONE,
            Some(Instant::now() + Duration::from_millis(50)),
        );
        assert_eq!(res, Err(moto_rt::E_TIMED_OUT), "wake delivered twice");
    });
    while handle_slot.load(Ordering::Acquire) == 0 {
        std::thread::sleep(Duration::from_millis(1));
    }
    (probe, SysHandle::from_u64(handle_slot.load(Ordering::Acquire)))
}

fn test_wake_on_sleep_fold() {
    let (probe, handle) = spawn_wake_probe();

    // A single task parking on a timer: the executor folds the deferred
    // wake into its sleep syscall.
    moto_async::LocalRuntime::new().block_on(async move {
        moto_async::LocalRuntime::set_wake_on_sleep(handle);
        moto_async::sleep(Duration::from_millis(5)).await;
    });

    probe.join().unwrap();
    println!("----- moto_async::test_wake_on_sleep_fold PASS");
}

fn test_wake_on_sleep_poll_resume() {
    let (probe, handle) = spawn_wake_probe();

    // The task spins past its own 200us timer deadline, so the executor
    // finds an expired timer at its sleep decision and resumes polling
    // instead of parking: the deferred wake must be issued explicitly.
    moto_async::LocalRuntime::new().block_on(async move {
        let mut sleep = Box::pin(moto_async::sleep(Duration::from_micros(200)));
        let mut armed = false;
        futures::future::poll_fn(|cx| {
            if !armed {
                armed = true;
                moto_async::LocalRuntime::set_wake_on_sleep(handle);
            }
            match sleep.as_mut().poll(cx) {
                Poll::Ready(()) => Poll::Ready(()),
                Poll::Pending => {
                    let spin_until = Instant::now() + Duration::from_micros(400);
                    while Instant::now() < spin_until {
                        core::hint::spin_loop();
                    }
                    Poll::Pending
                }
            }
        })
        .await;
    });

    probe.join().unwrap();
    println!("----- moto_async::test_wake_on_sleep_poll_resume PASS");
}

pub fn run_all_tests() {
    test_basic();
    test_timeout();
    test_select();
    test_spawn();
    test_interleaving();
    test_nested_tasks();
    test_event_stream();
    test_wake_exit_race();
    test_mutex();
    test_mutex_cancel_safety();
    test_oneshot();
    test_channel_basic();
    test_moto_channel_multithreaded();
    test_futures_channel_multithreaded();
    test_sync_waiter_signal_coalescing();
    test_sync_waiter_cross_thread();
    test_sync_waiter_ping_pong();
    test_block_on_sync_ready();
    test_block_on_sync_cross_thread();
    test_block_on_sync_self_wake();
    test_block_on_sync_deadline();
    test_local_notify_eager();
    test_local_notify_deferred();
    test_local_notify_multi_waiter();
    test_local_notify_cancel_redispatch();
    test_local_notify_notify_all_cancel();
    test_wake_elision_counters();
    test_for_each_concurrent();
    test_wake_on_sleep_fold();
    test_wake_on_sleep_poll_resume();

    println!("moto_async all PASS");
}
